#!/bin/bash

## GET DB CONFIG
getdb_config() {
  bacula_conf=`sed '/^#/d' /etc/bacula/bacula-dir.conf`
  bacula_conf=`echo "$bacula_conf" | grep dbname`
  bacula_conf=`echo "$bacula_conf" | sed 's/ //g' | sed 's/;/\n/g' > /tmp/bacula_conf`
  source /tmp/bacula_conf
  if [ "$DBAddress" == "" ]
  then
    DBAddress="localhost"
  fi
}

## GET ACTIVE JOB NAMES
getjob_names()
{
    until [ -z "$1" ]
    do
      if [ ${1:0} != 'Job:' ]
      then
          tmp=${1:0}               
          parameter=${tmp%%=*}     
          value=${tmp##*=}         
          eval $parameter=$value
      fi
      shift
    done
    if [ $Enabled == '1' ]
    then
      echo $name
    fi
}

## GET EACH JOB STATUS, BYTES, LEVEL AND LAST EXECUTION
getjob_status()
{
  for i in $*
  do
    status_job=$(export PGPASSWORD=$dbpassword && /usr/bin/psql -h$DBAddress -U$dbuser -d$dbname -t -c "SELECT concat_ws(',',jobstatus,jobbytes,level,EXTRACT(EPOCH FROM NOW()-EndTime)::integer) FROM Job WHERE name='$i' ORDER BY jobid DESC LIMIT 1 OFFSET 0"|xargs)
    job_status="$i,$status_job"
    echo $job_status >> /tmp/jobs_discovery.txt
  done
}

## GENERATE AUTO DISCOVERY JSON
generate_zabbix_json()
{
  LINHAS=$(cat /tmp/jobs_discovery.txt|wc -l)
  echo -e "{" > /tmp/jobs_discovery_lld.txt
  echo -e "\t\"data\":[\n" >> /tmp/jobs_discovery_lld.txt
  for ((i=1; i<$LINHAS; i++))
  do
    echo -e "\t{" >> /tmp/jobs_discovery_lld.txt
    echo -e "\t\t\"{#JOB}\":\"`cat /tmp/jobs_discovery.txt | head -$i | tail -1 | cut -d',' -f1`\"," >> /tmp/jobs_discovery_lld.txt
    echo -e "\t\t\"{#JOBSTATUS}\":\"`cat /tmp/jobs_discovery.txt | head -$i | tail -1 | cut -d',' -f2`\"," >> /tmp/jobs_discovery_lld.txt
    echo -e "\t\t\"{#JOBBYTES}\":\"`cat /tmp/jobs_discovery.txt | head -$i | tail -1 | cut -d',' -f3`\"," >> /tmp/jobs_discovery_lld.txt
    echo -e "\t\t\"{#JOBLEVEL}\":\"`cat /tmp/jobs_discovery.txt | head -$i | tail -1 | cut -d',' -f4`\"," >> /tmp/jobs_discovery_lld.txt
    echo -e "\t\t\"{#LASTEXECUTION}\":\"`cat /tmp/jobs_discovery.txt | head -$i | tail -1 | cut -d',' -f5`\"" >> /tmp/jobs_discovery_lld.txt
    echo -e "\t}" >> /tmp/jobs_discovery_lld.txt
    echo -e "\t," >> /tmp/jobs_discovery_lld.txt
  done
  echo -e "\t{" >> /tmp/jobs_discovery_lld.txt
  echo -e "\t\t\"{#JOB}\":\"`cat /tmp/jobs_discovery.txt | head -$LINHAS | tail -1 | cut -d',' -f1`\"," >> /tmp/jobs_discovery_lld.txt
  echo -e "\t\t\"{#JOBSTATUS}\":\"`cat /tmp/jobs_discovery.txt | head -$LINHAS | tail -1 | cut -d',' -f2`\"," >> /tmp/jobs_discovery_lld.txt
  echo -e "\t\t\"{#JOBBYTES}\":\"`cat /tmp/jobs_discovery.txt | head -$LINHAS | tail -1 | cut -d',' -f3`\"," >> /tmp/jobs_discovery_lld.txt
  echo -e "\t\t\"{#JOBLEVEL}\":\"`cat /tmp/jobs_discovery.txt  | head -$LINHAS | tail -1 | cut -d',' -f4`\"" >> /tmp/jobs_discovery_lld.txt
  echo -e "\t\t\"{#LASTEXECUTION}\":\"`cat /tmp/jobs_discovery.txt  | head -$LINHAS | tail -1 | cut -d',' -f5`\"" >> /tmp/jobs_discovery_lld.txt
  echo -e "\t}\n" >> /tmp/jobs_discovery_lld.txt
  echo -e "\t]" >> /tmp/jobs_discovery_lld.txt
  echo -e "}\n" >> /tmp/jobs_discovery_lld.txt
}

## EXECUTION
getdb_config
getjob_status $(echo "show job"|bconsole|grep Job:|while read LINE;do getjob_names $LINE;done)
generate_zabbix_json
cat /tmp/jobs_discovery_lld.txt